#!/usr/bin/env bash
#info chanel
if [ -f $School ];
then 
echo "school file exists"
else
echo "school file does not exist"
fi
if [ -s $School ];
then
echo "school file is not empty"
else 
echo "school file is empty"
fi
if [ -f $shool];
then
echo "school is a regular file"
fi
